#job-eks-cron-hourly.yaml

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-bench-cron-hourly
  namespace: {{ .Values.namespace }}
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: {{ .Values.logRetention.hourly }}
  failedJobsHistoryLimit: {{ .Values.logRetention.hourly }}
  jobTemplate:
    metadata:
      namespace: {{ .Values.namespace }}
    spec:
      template:
        metadata:
          namespace: {{ .Values.namespace }}
          labels:
            EksGatekeeper: {{ .Values.EksGatekeeper }}
        spec:
          hostPID: true
{{- if .Values.image.imagePullSecrets.enabled }}
          imagePullSecrets:
          - name: {{ .Values.image.imagePullSecrets.name }}
{{- end }}
          containers:
            - name: kube-bench-hourly
              image: {{ .Values.image.repository }}:{{ .Values.image.release }}
              command: ["kube-bench", "node", "--benchmark", "{{ .Values.benchmark }}"]
              volumeMounts:
                - name: var-lib-kubelet
                  mountPath: /var/lib/kubelet
                  readOnly: true
                - name: etc-systemd
                  mountPath: /etc/systemd
                  readOnly: true
                - name: etc-kubernetes
                  mountPath: /etc/kubernetes
                  readOnly: true
                - name: kube-bench-eks-config
                  mountPath: "/opt/kube-bench/cfg/eks-1.0/config.yaml"
                  subPath: config.yaml
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: var-lib-kubelet
              hostPath:
                path: "/var/lib/kubelet"
            - name: etc-systemd
              hostPath:
                path: "/etc/systemd"
            - name: etc-kubernetes
              hostPath:
                path: "/etc/kubernetes"
            - name: kube-bench-eks-config
